<?php

/**
 * BaseUserIdentification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $identification
 * @property integer $user_id
 * @property User $User
 * 
 * @method string             getIdentification() Returns the current record's "identification" value
 * @method integer            getUserId()         Returns the current record's "user_id" value
 * @method User               getUser()           Returns the current record's "User" value
 * @method UserIdentification setIdentification() Sets the current record's "identification" value
 * @method UserIdentification setUserId()         Sets the current record's "user_id" value
 * @method UserIdentification setUser()           Sets the current record's "User" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserIdentification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_identification');
        $this->hasColumn('identification', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}