<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $subject
 * @property string $message
 * @property boolean $is_public
 * @property boolean $is_activated
 * @property User $User
 * 
 * @method integer getUserId()       Returns the current record's "user_id" value
 * @method string  getSubject()      Returns the current record's "subject" value
 * @method string  getMessage()      Returns the current record's "message" value
 * @method boolean getIsPublic()     Returns the current record's "is_public" value
 * @method boolean getIsActivated()  Returns the current record's "is_activated" value
 * @method User    getUser()         Returns the current record's "User" value
 * @method Comment setUserId()       Sets the current record's "user_id" value
 * @method Comment setSubject()      Sets the current record's "subject" value
 * @method Comment setMessage()      Sets the current record's "message" value
 * @method Comment setIsPublic()     Sets the current record's "is_public" value
 * @method Comment setIsActivated()  Sets the current record's "is_activated" value
 * @method Comment setUser()         Sets the current record's "User" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('message', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '500',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}