<?php

/**
 * BaseUnixAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $hostname
 * @property integer $quota
 * @property User $User
 * 
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method string      getHostname() Returns the current record's "hostname" value
 * @method integer     getQuota()    Returns the current record's "quota" value
 * @method User        getUser()     Returns the current record's "User" value
 * @method UnixAccount setUserId()   Sets the current record's "user_id" value
 * @method UnixAccount setHostname() Sets the current record's "hostname" value
 * @method UnixAccount setQuota()    Sets the current record's "quota" value
 * @method UnixAccount setUser()     Sets the current record's "User" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUnixAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unix_account');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('hostname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('quota', 'integer', null, array(
             'type' => 'integer',
             'default' => '500000',
             ));


        $this->index('account', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'hostname',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}