<?php


/**
 * This class adds structure of 'ftp_account' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Mar 26 22:24:00 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FtpAccountMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FtpAccountMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(FtpAccountPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(FtpAccountPeer::TABLE_NAME);
		$tMap->setPhpName('FtpAccount');
		$tMap->setClassname('FtpAccount');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'user', 'ID', true, null);

		$tMap->addColumn('UP_BANDWIDTH', 'UpBandwidth', 'INTEGER', false, null);

		$tMap->addColumn('DOWN_BANDWIDTH', 'DownBandwidth', 'INTEGER', false, null);

		$tMap->addColumn('IP_ACCESS', 'IpAccess', 'VARCHAR', false, 255);

		$tMap->addColumn('QUOTA_SIZE', 'QuotaSize', 'INTEGER', false, null);

		$tMap->addColumn('QUOTA_FILES', 'QuotaFiles', 'INTEGER', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // FtpAccountMapBuilder
