<?php


/**
 * This class adds structure of 'user' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Sep 20 13:54:47 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UserMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UserMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UserPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UserPeer::TABLE_NAME);
		$tMap->setPhpName('User');
		$tMap->setClassname('User');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('DOMAINNAME_ID', 'DomainnameId', 'INTEGER', 'domainname', 'ID', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 255);

		$tMap->addColumn('FATHERS_NAME', 'FathersName', 'VARCHAR', true, 255);

		$tMap->addColumn('GRAND_FATHERS_NAME', 'GrandFathersName', 'VARCHAR', true, 255);

		$tMap->addColumn('LOGIN', 'Login', 'VARCHAR', true, 50);

		$tMap->addColumn('PHONE', 'Phone', 'VARCHAR', false, 255);

		$tMap->addColumn('NT_PASSWORD', 'NtPassword', 'VARCHAR', false, 255);

		$tMap->addColumn('LM_PASSWORD', 'LmPassword', 'VARCHAR', false, 255);

		$tMap->addColumn('CRYPT_PASSWORD', 'CryptPassword', 'VARCHAR', false, 255);

		$tMap->addColumn('UNIX_PASSWORD', 'UnixPassword', 'VARCHAR', false, 255);

		$tMap->addColumn('GID', 'Gid', 'INTEGER', true, null);

		$tMap->addColumn('UID', 'Uid', 'INTEGER', true, null);

		$tMap->addColumn('STATUS', 'Status', 'VARCHAR', true, 20);

		$tMap->addColumn('ALTERNATE_EMAIL', 'AlternateEmail', 'VARCHAR', false, 255);

		$tMap->addColumn('EMAIL_LOCAL_PART', 'EmailLocalPart', 'VARCHAR', true, 255);

		$tMap->addColumn('EMAIL_QUOTA', 'EmailQuota', 'VARCHAR', true, 32);

		$tMap->addColumn('EXPIRES_AT', 'ExpiresAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // UserMapBuilder
