<?php

/**
 * SambaAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class SambaAccount extends BaseSambaAccount
{
	public function getSmbpasswdLine()
	{
		return $this->getUser()->getLogin() . ":" .
			$this->getUser()->getUid() . ":" .
			$this->getUser()->getLmPassword() . ":" .
			$this->getUser()->getNtPassword() . ":" .
			"[U          ]:" .
			"LCT-" . dechex(strtotime($this->getUser()->getUpdatedAt()));
	}
}
