<?php

/**
 * UserIdentification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UserIdentification extends BaseUserIdentification
{
    public function getUserFullname()
    {
            return $this->getUser()->__toString();
    }
}
