propel:
  domainname:
    id:           ~
    name:         { type: varchar(255), required: true, index: unique }

  user:
    id:           ~
    domainname_id:    { type: integer, foreignTable: domainname, foreignReference: id, required: true, onDelete: cascade }
    name:   { type: varchar(255), required: true, index: true }
    fathers_name: { type: varchar(255), required: true, index: true }
    grand_fathers_name: { type: varchar(255), required: true, index: true }
    login:        { type: varchar(50), required: true, index: unique }
    phone:        { type: varchar(255) }
    nt_password:  { type: varchar(255) }
    lm_password:  { type: varchar(255) }
    crypt_password: { type: varchar(255) }
    unix_password: { type: varchar(255) }
    gid:          { type: integer, required: true }
    uid:          { type: integer, required: true, index: unique }
    status:       { type: varchar(20), required: true, default: 'disactivated' }
    alternate_email: { type: varchar(255) }
    email_local_part:   { type: varchar(255), required: true }
    email_quota:        { type: varchar(32), required: true, default: '500000S' }
    expires_at:   { type: timestamp, required: true }
    created_at:   ~
    updated_at:   ~
    _uniques:
        email_address: [email_local_part, domainname_id]
    
  user_identification:
    id:           ~
    identification:       { type: varchar(255), unique: true } 
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true, onDelete: cascade }
  
  unix_account:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true, onDelete: cascade } 
    hostname:     { type: varchar(255), required: true, index: true }
    quota:        { type: integer, default: '500000' }
    created_at:   ~
    updated_at:   ~
    _uniques:     { account: [user_id, hostname] }

  ftp_account:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true, onDelete: cascade } 
    up_bandwidth: { type: integer, default: 0 }
    down_bandwidth: { type: integer, default: 0 }
    ip_access:    { type: varchar(255), default: '*' }
    quota_size:   { type: integer, default: 0}
    quota_files:  { type: integer, default: 0}
    created_at:   ~
    updated_at:   ~

  samba_account:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true, onDelete: cascade }
    hostname:     { type: varchar(255), required: true, index: true }
    created_at:   ~
    updated_at:   ~
    _uniques:     { account: [user_id, hostname] }

  email_alias:
    id:           ~
    local_part:   { type: varchar(255), required: true, index: true }
    domainname_id:    { type: integer, foreignTable: domainname, foreignReference: id, required: true, onDelete: cascade }
    destination:  { type: varchar(255), required: true }
    created_at:   ~
    updated_at:   ~
    _uniques:     { email_alias: [local_part, domainname_id, destination] }
